receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  jaeger_storage_exporter:
    trace_storage: memory-store

service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_storage:
    backends:
      memory-store:
        memory:
          max_traces: 200000
  jaeger_query:
    base_path: /jaeger
    storage:
      traces: memory-store
